### ISSUE TITLE
Can I use uC-FS to implement romFS？

### ISSUE THREAD

**Issue by CheneyDu0129** [weston-embedded/uC-FS#1]
Now I need a romFS， Can I use uC-FS to implement it？
Is there an example?

**Comment by SeanAlling** [comment]
Assuming a [RAM file system](https://doc.micrium.com/display/fsdoc/RAM+Disk+Driver), this is supported in uC/FS. 

In the uc/FS documentation you shall find an [example](https://doc.micrium.com/display/fsdoc/Using+the+RAM+Disk+Driver) of using the RAM file system. At a minimum, you just need to provide the driver files for reading and writing to RAM. Link the driver functions to the RAM FS and then the rest of it shall just work.

**Comment by CheneyDu0129** [comment]
> Assuming a [RAM file system](https://doc.micrium.com/display/fsdoc/RAM+Disk+Driver), this is supported in uC/FS.
> 
> In the Uc/FS documentation you shall find an [example](https://doc.micrium.com/display/fsdoc/Using+the+RAM+Disk+Driver) of using the RAM file system. At a minimum, you just need to provide the driver files for reading and writing to RAM. Link tghe driver functions to the RAM FS and then the rest of it shall just work.

Thank you for your answer.
I already have RAMFS in use, but at present I expect to have a ROMFS for storing embedded web pages. Is there a way to implement ROMFS?

**Comment by SeanAlling** [comment]
There are two cases for a ROM FS, static or dynamic. 

# Static FS

Static FS support is built into uc-HTTP, and not directly into uC-FS.

An updated guide for using HTTPs and a static file system can be found in the [Micrium-OS documentation](https://doc.micrium.com/display/OSUM50400/HTTP+Server+Interface+with+File+System). A special [configuration ](https://github.com/Micrium/uC-HTTP/blob/master/Server/FS/Static/Cfg/Template/http-s_fs_static_cfg.h) is required to enable static FS.

Key parts for a ROM FS is to convert files to binary arrays, which is done through [GenerateFS.py](https://github.com/Micrium/uC-HTTP/tree/master/Server/FS/Script). Simply run the script, and then include the resulting files in your project.

# Dynamic FS

In contrast to a static FS, the dynamic FS is built directly into uC-FS. There are two options, NAND and NOR. Simply provide the drivers and enable the modules in uC-FS.

**Comment by CheneyDu0129** [comment]
Thank you.
I will try porting the static file system to the VFS layer of UC-FS.
because I didn't use uC/TCP and uC/HTTP.
