### ISSUE TITLE
SD card driver doesn't always align buffers with FS_CFG_BUF_ALIGN_OCTETS

### ISSUE THREAD

**Issue by clinton-r** [weston-embedded/uC-FS#9]
Sometimes buffers supplied from driver functions aren't aligned at address multiples of FS_CFG_BUF_ALIGN_OCTETS (from fs_cfg.h).
A couple of examples:
- FSDev_SD_Card_SetBusWidth() passes the buffer "scr" to FSDev_SD_Card_SendSCR(), which is eventually passed to my FSDev_SD_Card_BSP_CmdStart() function.  "scr" is allocated on the stack and not aligned.
- FSDev_SD_Card_SetBusWidth() passes the buffer "sd_status" to FSDev_SD_Card_SendSDStatus(), which is eventually passed to my FSDev_SD_Card_BSP_CmdStart() function.  "sd_status" is allocated on the stack and not aligned.

**Comment by forg0ne** [comment]
Unfortunately, this is a limitation of the SD driver in its current form.
The workaround is to have the BSP create an aligned buffer for dma operations.
If the FS passes a buffer with the proper alignment, you can simply read into that buffer.
If the buffer is not properly aligned, you need to read into the aligned buffer first, then perform a mem copy from there to the destination buffer.
